// Sends SMS and email for every Threadline API. Configure it in each API's .env:
//   Phone  SMS_PROVIDER=android sends every SMS (sign-up/login codes included) from your own Android phone's SIM, with
//          no SMS company: install SMS Gateway for Android (https://sms-gate.app) on the phone, turn on its Local
//          Server, and set ANDROID_SMS_URL (e.g. http://192.168.1.20:8080, as the app shows), ANDROID_SMS_USER and
//          ANDROID_SMS_PASSWORD. The phone must stay on, connected to the same network as the API.
//   SMS    SMS_PROVIDER=fast2sms with FAST2SMS_API_KEY (and optionally FAST2SMS_ROUTE) sends through Fast2SMS.
// Every code (sign-up/login OTPs, delivery OTPs, pickup and return codes) is generated by the API and sent as a
// normal SMS through whichever provider is set.
//   Email  SMTP_HOST, SMTP_PORT, SMTP_SECURE, SMTP_USER, SMTP_PASSWORD and optionally SMTP_FROM
//          (for Gmail: smtp.gmail.com, 465, true, your address and an App Password)
// For local testing without accounts, OTP_DEV_CONSOLE=true prints every message to the API console instead
// (never in production).
import nodemailer from 'nodemailer'

const env = (name) => String(process.env[name] || '').trim()
const devConsole = () => env('OTP_DEV_CONSOLE') === 'true' && process.env.NODE_ENV !== 'production'
const smsProvider = () => env('SMS_PROVIDER').toLowerCase() || (env('FAST2SMS_API_KEY') ? 'fast2sms' : '')
const androidGateway = () => env('ANDROID_SMS_URL').replace(/\/+$/, '')
const smsCredentials = () => ({
  android: Boolean(androidGateway() && env('ANDROID_SMS_USER') && env('ANDROID_SMS_PASSWORD')),
  fast2sms: Boolean(env('FAST2SMS_API_KEY')),
})[smsProvider()] || false
const emailCredentials = () => Boolean(env('SMTP_HOST') && env('SMTP_USER') && env('SMTP_PASSWORD'))

export const smsConfigured = () => smsCredentials() || devConsole()
export const emailConfigured = () => emailCredentials() || devConsole()

// Indian mobile numbers are stored as 10 digits.
const tenDigits = (phone) => String(phone || '').replace(/\D/g, '').slice(-10)

async function sendFast2Sms(phone, text) {
  // The Quick SMS route ("q") sends free text without DLT templates. Set FAST2SMS_ROUTE if your account uses another.
  const response = await fetch('https://www.fast2sms.com/dev/bulkV2', {
    method: 'POST',
    headers: { authorization: env('FAST2SMS_API_KEY'), 'Content-Type': 'application/json' },
    body: JSON.stringify({ route: env('FAST2SMS_ROUTE') || 'q', message: text, language: 'english', flash: 0, numbers: tenDigits(phone) }),
  })
  const result = await response.json().catch(() => ({}))
  if (!response.ok || result.return !== true) throw new Error(`Fast2SMS: ${[].concat(result.message || response.status).join(' ')}`)
}

// SMS Gateway for Android, Local Server mode: the phone itself sends the text from its SIM.
async function sendAndroidSms(phone, text) {
  const response = await fetch(`${androidGateway()}/message`, {
    method: 'POST',
    headers: { Authorization: `Basic ${Buffer.from(`${env('ANDROID_SMS_USER')}:${env('ANDROID_SMS_PASSWORD')}`).toString('base64')}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ message: text, phoneNumbers: [`+91${tenDigits(phone)}`] }),
    signal: AbortSignal.timeout(15_000),
  }).catch((error) => { throw new Error(`Android SMS gateway at ${androidGateway()} is unreachable (${error.message}). Is the phone on the same network with Local Server running?`) })
  if (!response.ok) throw new Error(`Android SMS gateway ${response.status}: ${(await response.text().catch(() => '')).slice(0, 200)}`)
}

export async function sendSms(phone, text) {
  if (!smsCredentials()) {
    if (devConsole()) return console.info(`[dev SMS to ${tenDigits(phone)}] ${text}`)
    throw new Error('SMS is not configured. Set SMS_PROVIDER=fast2sms with FAST2SMS_API_KEY, or SMS_PROVIDER=android with the ANDROID_SMS_* settings.')
  }
  return smsProvider() === 'android' ? sendAndroidSms(phone, text) : sendFast2Sms(phone, text)
}

let transporter
export async function sendEmail(to, subject, text) {
  if (!emailCredentials()) {
    if (devConsole()) return console.info(`[dev email to ${to}] ${subject}: ${text}`)
    throw new Error('Email is not configured. Set SMTP_HOST, SMTP_USER and SMTP_PASSWORD.')
  }
  transporter ??= nodemailer.createTransport({ host: env('SMTP_HOST'), port: Number(env('SMTP_PORT') || 587), secure: env('SMTP_SECURE') === 'true', auth: { user: env('SMTP_USER'), pass: env('SMTP_PASSWORD') } })
  await transporter.sendMail({ from: env('SMTP_FROM') || env('SMTP_USER'), to, subject, text })
}

// Order codes (delivery OTPs, pickup and return codes) go to every configured channel. Failures are logged, never
// thrown, so a message never fails the request that triggered it. Resolves to { sent }: true when at least one
// channel delivered it, which the "resend code" routes report back to the person asking.
export async function notify({ phone, email, subject, text }) {
  const jobs = []
  if (phone && smsConfigured()) jobs.push(sendSms(phone, text))
  if (email && emailConfigured()) jobs.push(sendEmail(email, subject, text))
  const results = await Promise.allSettled(jobs)
  results.filter((result) => result.status === 'rejected').forEach((result) => console.error('Notification failed:', result.reason?.message || result.reason))
  return { sent: results.some((result) => result.status === 'fulfilled') }
}

// One line at startup saying where messages go, so "I'm not getting the OTP" is easy to diagnose.
export function logMessagingSetup(service) {
  const fallback = devConsole() ? 'NOT CONFIGURED, printed in this console' : 'off'
  const sms = smsCredentials() ? (smsProvider() === 'android' ? `android (${androidGateway()})` : smsProvider()) : fallback
  const email = emailCredentials() ? `SMTP ${env('SMTP_HOST')}` : fallback
  console.info(`[${service}] SMS: ${sms} | Email: ${email}`)
}
