// SMS + email for the codes exchanged in person during a delivery or return. The codes are generated by the API and
// reach people only through these messages (they are never shown in the apps), so each function resolves to
// { sent } and the "resend code" routes let people ask again. Takes the models it needs instead of importing
// mongoose, like models.js.
import { notify } from './notify.js'

const orderNumber = (order) => String(order._id).slice(-8).toUpperCase()
const notSent = { sent: false }

// Shown in the apps instead of the code itself: where it was sent, e.g. "******4321".
export const maskedPhone = (phone) => {
  const digits = String(phone || '').replace(/\D/g, '').slice(-10)
  return digits ? `******${digits.slice(-4)}` : ''
}

// Stops one code being re-sent more than once every 30 seconds. In memory, so it resets when the API restarts.
const lastResend = new Map()
export function resendWait(key, seconds = 30) {
  const wait = Math.ceil((Number(lastResend.get(key) || 0) + seconds * 1000 - Date.now()) / 1000)
  if (wait > 0) return wait
  lastResend.set(key, Date.now())
  if (lastResend.size > 5000) lastResend.clear()
  return 0
}

// To the customer: the 4-digit code they give the person at the door. Sent to the delivery address's phone (the
// person receiving the parcel) and to the customer's account email.
export async function sendDeliveryOtp(Customer, order, { otp = order.deliveryOtp, deliveredBy = '', renewed = false } = {}) {
  if (!otp) return notSent
  const customer = await Customer.findById(order.customer).select('email').lean().catch(() => null)
  const number = orderNumber(order)
  const text = renewed
    ? `Threadline: your delivery OTP for order #${number} is ${otp}. Share it only when you receive your parcel.`
    : `Threadline: order #${number} is out for delivery${deliveredBy ? ` with ${deliveredBy}` : ''}. Share delivery OTP ${otp} only when you receive your parcel.`
  return notify({ phone: order.shippingAddress?.phone, email: customer?.email, subject: renewed ? `Delivery OTP for order #${number}` : `Order #${number} is out for delivery`, text })
}

// Return pickups. To the customer when a partner takes the pickup: the code they give the partner with the items.
export async function sendReturnCustomerCode(Customer, order, code, partner, { renewed = false } = {}) {
  const customer = await Customer.findById(order.customer).select('email').lean().catch(() => null)
  const number = orderNumber(order)
  const who = partner?.name ? `${partner.name}${partner.phone ? ` (${partner.phone})` : ''}` : 'our delivery partner'
  const text = renewed
    ? `Threadline: your return code for order #${number} is ${code}. Share it only when you hand over the item.`
    : `Threadline: ${who} will collect your return for order #${number}. Return code ${code}. Share it only when you hand over the item.`
  return notify({ phone: order.shippingAddress?.phone, email: customer?.email, subject: `Return pickup for order #${number}`, text })
}

// To the seller once the partner has collected the return: the code they give the partner on receiving it.
export async function sendReturnSellerCode(Seller, order, sellerId, code, partner, { renewed = false } = {}) {
  const seller = await Seller.findById(sellerId).select('email phone application.primaryPhone').lean().catch(() => null)
  if (!seller) return notSent
  const number = orderNumber(order)
  const who = partner?.name ? `${partner.name}${partner.phone ? ` (${partner.phone})` : ''}` : 'the delivery partner'
  const text = renewed
    ? `Threadline: your return code for order #${number} is ${code}. Give it only once you have received the returned items.`
    : `Threadline: ${who} is bringing back returned items from order #${number}. Return code ${code}. Give it only once you have received them.`
  return notify({ phone: seller.application?.primaryPhone || seller.phone, email: seller.email, subject: `Return on its way for order #${number}`, text })
}

// To each seller: the pickup code they read to the delivery partner when handing over their items.
export async function sendPickupCodes(Seller, order, handovers, partner, { renewed = false } = {}) {
  const pending = (handovers || []).filter((handover) => !handover.pickedUpAt)
  if (!pending.length) return notSent
  const sellers = await Seller.find({ _id: { $in: pending.map((handover) => handover.seller) } }).select('email phone application.primaryPhone').lean().catch(() => [])
  const number = orderNumber(order)
  const who = partner?.name ? `${partner.name}${partner.phone ? ` (${partner.phone})` : ''}` : 'the delivery partner'
  const results = await Promise.all(pending.map((handover) => {
    const seller = sellers.find((entry) => String(entry._id) === String(handover.seller))
    if (!seller) return notSent
    const text = renewed
      ? `Threadline: your pickup code for order #${number} is ${handover.otp}. Give it to ${who} only when you hand over the parcel.`
      : `Threadline: ${who} will collect order #${number}. Pickup code ${handover.otp}. Give it only when you hand over the parcel.`
    return notify({ phone: seller.application?.primaryPhone || seller.phone, email: seller.email, subject: `Pickup code for order #${number}`, text })
  }))
  return { sent: results.some((result) => result.sent) }
}
